<div class="share-links">
    <div class="share-email">
        <a href="#">Email to Friends</a>
    </div>
    <div class="addthis_sharing_toolbox">
        <p class="big-text">Share</p>
        <div class="f-social">
            <ul>
                <li>
                    <a href="http://www.facebook.com/sharer.php?u=" target="_blank"><i class="fa fa-facebook"></i></a>
                </li>
                 <li>
                    <a href="https://twitter.com/share?url=" target="_blank"><i class="fa fa-twitter"></i></a>
                </li>
                <li>
                    <a href="https://plus.google.com/share?url=" target="_blank"><i class="fa fa-pinterest-p"></i></a>
                </li>
                <li>
                    <a href="http://instagram.com/" target="_blank"><i class="fa fa-instagram"></i></a>
                </li>
            </ul>
        </div>
    </div>
</div>
