<div class="footer-content">
	<div class="about-us">
		<a href="">
			<img src='<?php echo $this->getViewFileUrl('images/logo1.png'); ?>' alt="Footer-Logo">>
		</a>
		<p class="content">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum est est, tempor sed est non, dapibus interdum nibh. Fusce nec tellus vestibulum, finibus lectus pulvinar, tempor massa. Nullam id neque sapien. Nullam aliquet nec metus vel pulvinar</p>
		<ul class="info">
			<li>
				<i class="fa fa-map-marker" aria-hidden="true"></i>
			</li>
			<li>
				<i class="fa fa-phone" aria-hidden="true"></i>
			</li>
			<li>
				<i class="fa fa-fax" aria-hidden="true"></i>
			</li>
			<li>
				<i class="fa fa-envelope" aria-hidden="true"></i>
			</li>
		</ul>
	</div>
	<div class="footer-main">
		<div class="menu">
			<div class="category">
				<h4>Category</h4>
				<ul>
					<li>
						<a href="">Vegetables</a>
					</li>
					<li>
						<a href="">Fruits</a>
					</li>
					<li>
						<a href="">Animals</a>
					</li>
					<li>
						<a href="">Organic Foods</a>
					</li>
				</ul>
			</div>
			
			<div class="infomation">
				<h4>Infomation</h4>
				<ul>
					<li>
						<a href="">Returns</a>
					</li>
					<li>
						<a href="">Delivery</a>
					</li>
					<li>
						<a href="">Services</a>
					</li>
					<li>
						<a href="">Gift Cards</a>
					</li>
					<li>
						<a href="">Manufacturers</a>
					</li>
					<li>
						<a href="">Discount Code</a>
					</li>
				</ul>
			</div>
			
			<div class="policies">
				<h4>Policies</h4>
				<ul>
					<li>
						<a href="">Terms Of Service</a>
					</li>
					<li>
						<a href="">Privacy</a>
					</li>
					<li>
						<a href="">Security</a>
					</li>
					<li>
						<a href="">Term Of Use</a>
					</li>
				</ul>
			</div>
			<div class="find-us">
				<h4>Find Us</h4>
				<ul>
					<li>
						<a href=""><i class="fa fa-facebook-square" aria-hidden="true"></i>Facebook</a>
					</li>
					<li>
						<a href=""><i class="fa fa-twitter-square" aria-hidden="true">Twitter</i></a>
					</li>
					<li>
						<a href=""><i class="fa fa-google-plus-square" aria-hidden="true">Google</i></a>
					</li>
					<li>
						<a href=""><i class="fa fa-youtube" aria-hidden="true"></i>Youtube</a>
					</li>
					<li>
						<a href=""><i class="fa fa-linkedin-square" aria-hidden="true"></i>Linkedin</a>
					</li>
				</ul>
			</div>			
		</div>
	</div>
</div>