<div class="copyright">
	<div class="copyright-content">
		<div class="left">
			<p>Copyright <i class="fa fa-copyright" aria-hidden="true"></i> <span>Food</span><span>farm</span>.All Rights Reserved.Powered by <span>ArrowHitech.</span></p>
		</div>
		<div class="right">
			<img src="<?php echo $this->getViewFileUrl('images/payment.jpg'); ?>" alt="payment">
		</div>
	</div>
</div>
<script type="text/javascript">
	require(["jquery","slideSlick"],function($,slideSlick) {
		$(document).ready(function(){
			$('.slide-slick').slick({
				dots: false,
				infinite: true,
				speed: 300,
				slidesToShow: 4,
				slidesToScroll: 4,
				responsive: [
				{
					breakpoint: 1024,
					settings: {
						slidesToShow: 4,
						slidesToScroll: 4,
					}
				},
				{
					breakpoint: 900,
					settings: {
						slidesToShow: 3,
						slidesToScroll: 3
					}
				},
				{
					breakpoint: 640,
					settings: {
						slidesToShow: 2,
						slidesToScroll: 2,
						dots: true
					}
				},
				{
					breakpoint: 420,
					settings: {
						slidesToShow: 1,
						slidesToScroll: 1,
						dots: true
					}
				}
    // You can unslick at a given breakpoint now by adding:
    // settings: "unslick"
    // instead of a settings object
    ]
});
			$('.banner-slide').slick({
				dots: true,
				//autoplay: true,
				//autoplaySpeed: 3500
			});
			$('.testimonals-slide').slick({
				slidesToShow: 1,
				slidesToScroll: 1,
				arrows: false,
				asNavFor: '.img-dot-slide',
				// autoplay: true,
				// autoplaySpeed: 3500
			});
			$('.img-dot-slide').slick({
				slidesToShow: 10,
				slidesToScroll: 10,
				asNavFor: '.testimonals-slide',
				focusOnSelect: true,
				centerMode: true,
				// autoplay: true,
				// autoplaySpeed: 3500
			});
		});
	});
</script>
<script>
	require(["jquery"],function($){
		$(document).ready(function(){
			if($('.amslider-header-container').text().length < 12){
				$('.amslider-header-container').css("display", "none");
			}
		});
	});
</script>
<!-- <script>
	require(["jquery","slideSlick"],function($,slideSlick) {
		$(document).ready(function(){
			$('.testimonals-slide').slick({
				slidesToShow: 1,
				slidesToScroll: 1,
				arrows: false,
				fade: true,
				asNavFor: '.img-dot-slide'
			});
			$('.img-dot-slide').slick({
				slidesToShow: 1,
				slidesToScroll: 1,
				asNavFor: '.testimonals-slide',
				focusOnSelect: true
			});
		});
	});
</script> -->